version: '3.3'
services:
  catalog-web:
    image: apap-registry.cs.ui.ac.id/fachry.anwar/apap-033-catalog
    build:
      context: ./catalog
    restart: always
    ports:
      - "10189:8081"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    depends_on:
      - apapedia33-db
    networks:
      - frontend-network
      - backend-network
  order-web:
    image: apap-registry.cs.ui.ac.id/fachry.anwar/apap-033-order
    build:
      context: ./order
    restart: always
    ports:
      - "10190:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    depends_on:
      - apapedia33-db
    networks:
      - frontend-network
      - backend-network
  user-web:
    image: apap-registry.cs.ui.ac.id/fachry.anwar/apap-033-user
    build:
      context: ./user
    restart: always
    ports:
      - "10188:8082"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    depends_on:
      - apapedia33-db
    networks:
      - frontend-network
      - backend-network
  frontend-web:
    image: apap-registry.cs.ui.ac.id/fachry.anwar/apap-033-frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - "10191:8083"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    networks:
      - frontend-network
      - backend-network
  apapedia33-db:
    image: postgres:14-alpine
    ports:
      - "15188:5432"
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge